apiVersion: v1
kind: Service
metadata:
  name: wordpress-clb-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 80 # Service Port
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
