apiVersion: v1
kind: Service
metadata:
  name: wordpress-nlb-service
  labels: 
    app: wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer # Default - CLB
  selector:
    app: wordpress
    tier: frontend
  ports: 
    - port: 80 # Service Port