apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport-service
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
